#!/usr/bin/env bash
# FizzBuzz from 1 to 100

for i in {1..100}
do
    if (( i % 15 == 0 )); then
        # multiple of 3 and 5
        echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
        # multiple of 3 only
        echo "Fizz"
    elif (( i % 5 == 0 )); then
        # multiple of 5 only
        echo "Buzz"
    else
        # not a multiple of 3 or 5
        echo "$i"
    fi
done
