#!/usr/bin/env bash
# Display username, user id and home directory path for the user

# Read /etc/passwd and cut the required fields
while IFS=":" read -r user _ uid _ _ _ home _; do
    echo "$user:$uid:$home"
done < /etc/passwd
