#!/usr/bin/env bash
# Display the number of occurrences of each (IP, HTTP status code) pair in apache-access.log

awk '
  $1 ~ /^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$/ &&
  $9 ~ /^[0-9][0-9][0-9]$/ {
    key = $1 " " $9
    count[key]++
  }
  END {
    for (k in count) print count[k], k
  }
' apache-access.log | sort -k1,1nr -k2,2 -k3,3
