#!/usr/bin/env bash
# Display the number of occurrences of each (IP, HTTP status) pair in apache-access.log

awk '
NF >= 9 && $1 ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ {
  code = $9
  gsub(/\r/, "", code)          # handle CRLF line endings
  if (code ~ /^[0-9]{3}$/) {
    key = $1 " " code
    count[key]++
  }
}
END {
  for (k in count) {
    print count[k], k
  }
}
' apache-access.log | sort -nr -k1,1 -k2,2V -k3,3n
