#!/usr/bin/env bash
# Display the number of occurrences of each (IP, HTTP status code) pair in apache-access.log

awk '{ print $1, $9 }' apache-access.log \
  | sort \
  | uniq -c \
  | sort -nr \
  | awk '{ printf "%5d %s %s\n", $1, $2, $3 }'
